# Generated by Django 5.0 on 2023-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='ID_ImgOne',
            field=models.ImageField(blank=True, upload_to='users/user/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ID_ImgTow',
            field=models.ImageField(blank=True, upload_to='users/user/ImgTow/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='National_ID',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
