# Generated by Django 5.0 on 2023-12-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
