# Generated by Django 4.2.10 on 2024-02-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=55555555555555555555555),
            preserve_default=False,
        ),
    ]
