# Generated by Django 4.2.10 on 2024-02-24 15:44

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id_imgone_alter_profile_id_imgtow_and_more'),
        ('MainPage', '0004_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('comment', models.TextField(blank=True, null=True)),
                ('vote', models.CharField(choices=[('up', 'Up Vote'), ('down', 'down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
