# Generated by Django 4.2.10 on 2024-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_bookreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='vote',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='rate',
            field=models.IntegerField(default=0),
        ),

    ]
