# Generated by Django 4.2.10 on 2024-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_remove_cartitem_rentdays_cartitem_is_rented_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_rented',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dealing_type',
            field=models.CharField(choices=[('buying', 'buying'), ('rental', 'rental')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
