# Generated by Django 4.2.10 on 2024-03-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id_imgone_alter_profile_id_imgtow_and_more'),
        ('MainPage', '0011_remove_cartitem_is_rented_cartitem_dealing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainPage.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='dealing_type',
            field=models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='rental_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
