# Generated by Django 4.2.10 on 2024-03-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id_imgone_alter_profile_id_imgtow_and_more'),
        ('MainPage', '0012_remove_cart_items_cart_book_cart_dealing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
