# Generated by Django 4.2.10 on 2024-03-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id_imgone_alter_profile_id_imgtow_and_more'),
        ('MainPage', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='high_rate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='retal_period',
        ),
        migrations.RemoveField(
            model_name='book',
            name='times_purchased',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='dealing_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rental_days',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealing_type', models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], max_length=50)),
                ('rental_days', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainPage.transaction'),
            preserve_default=False,
        ),
    ]
