# Generated by Django 4.2.10 on 2024-03-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0017_transaction_rental_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together=set(),
        ),
    ]
